### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by andrew7baker** [andrew7baker/smt-ui#2]
![image](https://user-images.githubusercontent.com/50053092/76675623-2a0bd480-65f6-11ea-9053-81e69381f3c5.png)

**Comment by andrew7baker** [comment]
npm run build:prod


> Cloud-Admin@1.2.0 build:prod /Users/qk/mygithub/vue-ui
> cross-env NODE_ENV=production node build/build.js

production
⠋ building for production.../Users/qk/mygithub/vue-ui/node_modules/last-call-webpack-plugin/src/index.js:170
    compiler.hooks.compilation.tap(
                   ^

TypeError: Cannot read property 'compilation' of undefined
    at OptimizeCssAssetsWebpackPlugin.apply (/Users/qk/mygithub/vue-ui/node_modules/last-call-webpack-plugin/src/index.js:170:20)
    at Compiler.apply (/Users/qk/mygithub/vue-ui/node_modules/webpack/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/qk/mygithub/vue-ui/node_modules/webpack/lib/webpack.js:32:19)
    at err (/Users/qk/mygithub/vue-ui/build/build.js:20:5)
    at next (/Users/qk/mygithub/vue-ui/node_modules/rimraf/rimraf.js:74:7)
    at CB (/Users/qk/mygithub/vue-ui/node_modules/rimraf/rimraf.js:110:9)
    at /Users/qk/mygithub/vue-ui/node_modules/rimraf/rimraf.js:136:14
    at FSReqWrap.oncomplete (fs.js:154:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Cloud-Admin@1.2.0 build:prod: `cross-env NODE_ENV=production node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Cloud-Admin@1.2.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qk/.npm/_logs/2020-03-14T05_16_50_096Z-debug.log
➜  vue-ui git:(master) clear
➜  vue-ui git:(master) npm run build:prod

> Cloud-Admin@1.2.0 build:prod /Users/qk/mygithub/vue-ui
> cross-env NODE_ENV=production node build/build.js

production
⠋ building for production.../Users/qk/mygithub/vue-ui/node_modules/last-call-webpack-plugin/src/index.js:170
    compiler.hooks.compilation.tap(
                   ^

TypeError: Cannot read property 'compilation' of undefined
    at OptimizeCssAssetsWebpackPlugin.apply (/Users/qk/mygithub/vue-ui/node_modules/last-call-webpack-plugin/src/index.js:170:20)
    at Compiler.apply (/Users/qk/mygithub/vue-ui/node_modules/webpack/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/qk/mygithub/vue-ui/node_modules/webpack/lib/webpack.js:32:19)
    at err (/Users/qk/mygithub/vue-ui/build/build.js:20:5)
    at next (/Users/qk/mygithub/vue-ui/node_modules/rimraf/rimraf.js:74:7)
    at CB (/Users/qk/mygithub/vue-ui/node_modules/rimraf/rimraf.js:110:9)
    at /Users/qk/mygithub/vue-ui/node_modules/rimraf/rimraf.js:136:14
    at FSReqWrap.oncomplete (fs.js:154:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Cloud-Admin@1.2.0 build:prod: `cross-env NODE_ENV=production node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Cloud-Admin@1.2.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
